/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourseSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'status', 'title', 'updatedAt'] as const
  $columns = CourseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MaterialDerivativeSchema extends BaseModel {
  static $columns = ['createdAt', 'height', 'id', 'kind', 'materialId', 'mimeType', 'pageNumber', 'position', 'storageKey', 'updatedAt', 'width'] as const
  $columns = MaterialDerivativeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare materialId: number
  @column()
  declare mimeType: string
  @column()
  declare pageNumber: number | null
  @column()
  declare position: number
  @column()
  declare storageKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number
}

export class MaterialSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'mimeType', 'moduleId', 'originalFilename', 'position', 'processingErrorCode', 'processingStatus', 'size', 'storageKey', 'title', 'type', 'updatedAt'] as const
  $columns = MaterialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare moduleId: number
  @column()
  declare originalFilename: string
  @column()
  declare position: number
  @column()
  declare processingErrorCode: string | null
  @column()
  declare processingStatus: string
  @column()
  declare size: number
  @column()
  declare storageKey: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModuleSchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'description', 'id', 'position', 'title', 'updatedAt'] as const
  $columns = ModuleSchema.$columns
  @column()
  declare courseId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProcessingJobSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'id', 'kind', 'lastErrorCode', 'leaseExpiresAt', 'lockedAt', 'materialId', 'maxAttempts', 'status', 'updatedAt'] as const
  $columns = ProcessingJobSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare lastErrorCode: string | null
  @column.dateTime()
  declare leaseExpiresAt: DateTime | null
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare materialId: number
  @column()
  declare maxAttempts: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UploadSettingSchema extends BaseModel {
  static $columns = ['maxSizeBytes', 'type'] as const
  $columns = UploadSettingSchema.$columns
  @column()
  declare maxSizeBytes: number
  @column({ isPrimary: true })
  declare type: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
