/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AppAppAccountRouteImport } from './routes/_app/app_.account'
import { Route as AdminAdminCoursesIndexRouteImport } from './routes/_admin/admin/courses/index'
import { Route as AdminAdminCoursesCourseIdRouteImport } from './routes/_admin/admin/courses/$courseId'
import { Route as AdminAdminCoursesNewRouteImport } from './routes/_admin/admin/courses/new'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin/users/$userId'
import { Route as AdminAdminUsersNewRouteImport } from './routes/_admin/admin/users/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppAppAccountRoute = AppAppAccountRouteImport.update({
  id: '/app_/account',
  path: '/app/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminCoursesIndexRoute = AdminAdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCoursesCourseIdRoute =
  AdminAdminCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminCoursesNewRoute = AdminAdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersNewRoute = AdminAdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/app': typeof AppAppRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/app/account': typeof AppAppAccountRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AdminAdminCoursesNewRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/users/new': typeof AdminAdminUsersNewRoute
  '/admin/courses/': typeof AdminAdminCoursesIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppAppRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/app/account': typeof AppAppAccountRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AdminAdminCoursesNewRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/users/new': typeof AdminAdminUsersNewRoute
  '/admin/courses': typeof AdminAdminCoursesIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_app/app_/account': typeof AppAppAccountRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRoute
  '/_admin/admin/courses/new': typeof AdminAdminCoursesNewRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/_admin/admin/users/new': typeof AdminAdminUsersNewRoute
  '/_admin/admin/courses/': typeof AdminAdminCoursesIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/app'
    | '/admin/settings'
    | '/app/account'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/courses/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/admin/settings'
    | '/app/account'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/courses'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/login'
    | '/_admin/admin'
    | '/_app/app'
    | '/_admin/admin/settings'
    | '/_app/app_/account'
    | '/_admin/admin/'
    | '/_admin/admin/courses/$courseId'
    | '/_admin/admin/courses/new'
    | '/_admin/admin/users/$userId'
    | '/_admin/admin/users/new'
    | '/_admin/admin/courses/'
    | '/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_app/app_/account': {
      id: '/_app/app_/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/courses/': {
      id: '/_admin/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminAdminCoursesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/courses/$courseId': {
      id: '/_admin/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminAdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/courses/new': {
      id: '/_admin/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminAdminCoursesNewRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users/new': {
      id: '/_admin/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminAdminUsersNewRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCoursesCourseIdRoute: typeof AdminAdminCoursesCourseIdRoute
  AdminAdminCoursesNewRoute: typeof AdminAdminCoursesNewRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminUsersNewRoute: typeof AdminAdminUsersNewRoute
  AdminAdminCoursesIndexRoute: typeof AdminAdminCoursesIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCoursesCourseIdRoute: AdminAdminCoursesCourseIdRoute,
  AdminAdminCoursesNewRoute: AdminAdminCoursesNewRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminUsersNewRoute: AdminAdminUsersNewRoute,
  AdminAdminCoursesIndexRoute: AdminAdminCoursesIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppAppAccountRoute: typeof AppAppAccountRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppAppAccountRoute: AppAppAccountRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
